### ISSUE TITLE
Front-End 스크립트 정리

### ISSUE THREAD

**Issue by smaker** [funnyxe/sketchbook5#1]
정리해야 할 파일

- [ ] ajaxfileupload.js
- [ ] board.js
- [ ] bootstrap-wysiwyg.js
- [ ] editor.js
- [ ] editor_m.js
- [ ] editor_textarea.js
- [ ] editor_wysiwyg.js

**Comment by smaker** [comment]
ajaxfileupload.js 파일 정리 완료

#TODO: board.js 파일 정리
